services:
  app:
    build: .
    container_name: cableops-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://username:password@db:5432/mydb
      BETTER_AUTH_URL: http://localhost:3000
      BETTER_AUTH_SECRET: 73730e0a96da4726a07de7d898b16e5d5831e654c264cdf3fdbb1300c4ad53ed

  db:
    image: postgres:17-alpine
    container_name: mydb-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
